#! /bin/bash
if [ -f /usr/sbin/ufw ]
             then
                echo "# ufw Firewall is already installed"
		sudo ufw allow ssh
        	sudo ufw allow http
        	echo "# ufw Firewall ports for SSH and Http configured"

fi
if [ ! -f /usr/sbin/ufw ]
          	then
          	      echo "# ufw Firewall NOT installed, installing..."
          	      sudo apt-get install -y ufw 
          	      sudo ufw enable
          	      echo "# ufw Firewall installed and enabled"
             	      sudo ufw allow ssh
  		      sudo ufw allow http
        	      echo "# ufw Firewall ports for SSH and Http configured"
fi
